---
- name: cleanup
  hosts: all
  gather_facts: false
  become: true
  vars:
    three_tier_packages:
      - httpd
      - python-pip
      - haproxy
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps
      - postgresql-server

  tasks:

    - name: reverse the enabling of sudo without tty for some ansible commands
      replace:
        path: /etc/sudoers
        regexp: 'Defaults\s*!requiretty'
        replace: '^Defaults requiretty'
        backup: yes

    - name: Remove the repo file
      file:
        state: absent
        path: /etc/yum.repos.d/open_three-tier-app.repo

    - name: Remove Apache Ant
      file:
        path: "{{ apache_ant_dir }}"
        state: absent
        force: yes
      when:
        - inventory_hostname is search('app1.*.internal') or inventory_hostname is search('app2.*.internal')

    - name: Remove Tomcat Deployer
      file:
        path: "{{ tomcat_deployer_dir }}"
        state: absent
        force: yes 
      when:
        - inventory_hostname is search('app1.*.internal') or inventory_hostname is search('app2.*.internal')

    - name: Stop services on "frontend1.{{GUID}}.internal"
      service:
        name: "haproxy"
        state: stopped
      when:
        - inventory_hostname is search('frontend1.*.internal')

    - name: Stop services on app machines
      service:
        name: "tomcat"
        state: stopped
      when:
        - inventory_hostname is search('app1.*.internal') or inventory_hostname is search('app2.*.internal')
  
    - name: Stop services on db machines
      service:
        name: "postgresql"
        state: stopped
      when:
        - inventory_hostname is search('appdb1.*.internal')

    - name: Remove base tools and three tier app packages
      yum:
        name: "{{ three_tier_packages }}"
        state: absent

    - name: Remove OpenJDK8 on apps machines
      yum:
        name: java-1.8.0-openjdk-devel
        state: absent
      when:
        - inventory_hostname is search('app1.*.internal') or inventory_hostname is search('app2.*.internal')

    - name: Remove index.html
      file:
        path: /tmp/index.html
        state: absent

    - name: Remove PostgreSQL directories
      file:
        name: /var/lib/pgsql
        state: absent
        force: true

    - name: Remove ANT environment variables script
      file:
        path: /root/ant_env.sh
        state: absent
      when:
        - inventory_hostname is search('app1.*.internal') or inventory_hostname is search('app2.*.internal')

