---
#
# Playbooks to setup 3-tier app
#

- name: Playbook for common tasks on all hosts
  hosts: all
  become: true

  roles:
    - { role: rd_ans_common, when: not inventory_hostname is search('bastion.*') }

- name: Playbook to deploy haproxy
  hosts: frontends
  become: true

  roles:
    - { role: rd_install_haproxy, }
    - { role: rd_config_haproxy, }

- name: Playbook to deploy Wildfly
  hosts: apps
  become: true

  roles:
    - { role: rd_setup_dbclient, }
    - { role: rd_install_wildfly, }
    - { role: rd_config_wildfly, }

- name: Playbook to setup PostgreSQL DB
  hosts: appdbs
  become: true

  roles:
    - { role: rd_setup_appdb, }
    - { role: rd_config_app_db, }

- name: Playbook to install 3-tier application to Wildfly
  hosts: apps
  become: true
 
  roles:
    - { role: rd_wildfly_app, }

