---
# tasks file for rd_ans_common
#
# Purpose:
# - Install common packages on hosts
#

- name: enable yum repos
  copy:
    src: files/project.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644
    decrypt: yes

