---
#
# Tasks to install Wildfly Server
#

- name: Download Wildfly Installer tar
  get_url:
    url: "{{wildfly_download_url}}"
    dest: /opt
    owner: root
    group: root

- name: Extract Wildfly Installer tar
  unarchive:
    src: "/opt/{{ wildfly_installer_file }}"
    dest: /opt/
    owner: root
    group: root
    remote_src: yes

- name: Create Soft link
  file:
    src: "{{ wildfly_install_dir }}"
    dest: "{{ wildfly_home_dir }}"
    state: link
    force: yes

- name: Delete Wildfly Installer tar
  file:
    path: "/opt/{{ wildfly_installer_file }}"
    state: absent

- name: Copy Wildfly Shutdown script
  template:
    src: shutdown_standalone.sh.j2
    dest: "{{wildfly_home_dir}}/bin/shutdown_standalone.sh"
    mode: 0755
    owner: root
    group: root

- name: Create service spec for Wildfly server
  template:
    src: wildfly.service.j2
    dest: /etc/systemd/system/wildfly.service

- name: Start Wildfly service
  systemd:
    name: wildfly.service
    state: started
    enabled: yes
    daemon_reload: yes

