---
# handlers file for rd_setup_appdb
#

- name: enable_postgresql
  service:
    name: postgresql
    enabled: yes

- name: start_postgresql
  service:
    name: postgresql
    state: started

- name: restart_postgresql
  service:
    name: postgresql
    state: restarted

